import type { Metadata } from "next";
import { Inter, League_Spartan } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const spartan = League_Spartan({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-spartan',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spartan.variable}`}
    >
      <body>
        {children}
      </body>
    </html>
  );
}
